services:
  gitlab:
    image: gitlab/gitlab-ce:18.1.6-ce.0
    container_name: devsecops-gitlab
    hostname: gitlab.local
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.local:8080'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:2222:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    shm_size: "256m"
    networks:
      - gitlab-net

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine-v18.1.0
    container_name: devsecops-gitlab-runner
    restart: unless-stopped
    depends_on:
      - gitlab
    volumes:
      - ./runner-config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab-net

networks:
  gitlab-net:
    name: devsecops-gitlab-net

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
